### ISSUE TITLE
Deployment to OpenShift failing

### ISSUE THREAD

**Issue by nickeblewis** [bartonhammond/snowflake-hapi-openshift#2]
Everything seems to go well until I run

$ git push origin master

remote: CLIENT_RESULT: HAProxy instance is started
remote:   - Checking to see if Node.js version 4.2.3 is installed ...
remote:   - Node.js version 4.2.3 is already installed
remote:
remote:   - pre_start_nodejs: Adding Node.js version 4.2.3 binaries to path
remote:   - PATH set to include custom node version (4.2.3) from
remote:        /var/lib/openshift/56a366ea2d527170ff0001e8/app-root/data//node-v4.2.3-linux-x64/bin
remote:     PATH = /var/lib/openshift/56a366ea2d527170ff0001e8/app-root/data//node-v4.2.3-linux-x64/bin:/var/lib/openshift/56a366ea2d527170ff0001e8/app-root/runtime/repo/node_modules/.bin:/var/lib/openshift/56a366ea2d527170ff0001e8//.node_modules/.bin:/opt/rh/nodejs010/root/usr/bin:/var/lib/openshift/56a366ea2d527170ff0001e8/haproxy/usr/bin:/opt/rh/mongodb24/root/usr/bin:/bin:/usr/bin:/usr/sbin
remote: Starting NodeJS cartridge
remote: Sat Jan 23 2016 06:51:33 GMT-0500 (EST): Starting application 'bespoke' ...
remote: Waiting for application port (8080) become available ...
remote: Application 'bespoke' failed to start (port 8080 not available)
remote: -------------------------
remote: Git Post-Receive Result: failure
remote: Activation status: failure
remote: Activation failed for the following gears:
remote: 56a366ea2d527170ff0001e8 (Error activating gear: CLIENT_ERROR: Failed to execute: 'control start' for /var/lib/openshift/56a366ea2d527170ff0001e8/nodejs
remote: #IO:0x000000009eb290
remote: #IO:0x000000009eb218
remote: )
remote: Deployment completed with status: failure
remote: postreceive failed
To ssh://56a366ea2d527170ff0001e8@bespoke-nicklewis.rhcloud.com/~/git/bespoke.git/
   08e1e01..15c5836  master -> master
# 

Any ideas as to why this could be? Should I configure the port differently?

Looks like a really good project and I am looking at how this can help me kickstart a project of mine.

Thanks,

Nick Lewis

**Comment by nickeblewis** [comment]
P.S. it does run locally on port 5000 ok

**Comment by bartonhammond** [comment]
Glad you like the project (be sure to Star it)...

1)be sure you have your config.js in src
2) be sure config.js is not in .gitignore
3) you can try restarting from the OpenShift dashboard too

let me know if that resolves it

**Comment by bartonhammond** [comment]
check this SO: [http://stackoverflow.com/questions/31511724/application-failed-to-start-port-8080-not-available](http://stackoverflow.com/questions/31511724/application-failed-to-start-port-8080-not-available) especially this step:

> ssh'd into the app, went to the app repo dir (cd $OPENSHIFT_REPO_DIR) and run npm start

**Comment by nickeblewis** [comment]
Thanks Barton - now when running npm start as suggested, I am getting:

/var/lib/openshift/56a366ea2d527170ff0001e8/app-root/runtime/repo/src/database/redis.js:27
  connection_string.host = process.env.OPENSHIFT_REDIS_DB_HOST;
                         ^

TypeError: Cannot set property 'host' of undefined
    at Object.<anonymous> (/var/lib/openshift/56a366ea2d527170ff0001e8/app-root/runtime/repo/src/database/redis.js:27:26)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/var/lib/openshift/56a366ea2d527170ff0001e8/app-root/runtime/repo/src/auth/jwt-strategy.js:20:19)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)

**Comment by bartonhammond** [comment]
Oh - my bad, I'll update...

The config.js should include:

```
  redis: {
    host: '127.0.0.1',
    port: 6379
  },
```

**Comment by nickeblewis** [comment]
Fantastic, got it working! Thanks for your help!

**Comment by aferust** [comment]
I am receiving same error. I am new one to js and web technologies. could you please give more detail about an example config.js. particularly I need to know what must be written for account name under email definition which is ''Snowflake" as default.

**Comment by bartonhammond** [comment]
@aferust - would you please include what your error currently is?

**Comment by aferust** [comment]
(Using OSX El Capitan on macbook pro)
after I wrote my previous message, I tried locally settled server option as you illustrated in the docs and got it working successfully. I want to get it working on openshift also. When I follow exactly the same steps as you have shown, I am receiving exactly same error, but I have just recognized that I am missing a lot about config.js. I have an openshift account and followed all the steps to "git push origin master" from the beginning. I am now pretty sure that I must provide appropriate ips (or urls maybe) and ports information for getting the app to connect the server (I think application was successfully created on my openshift account, because I can see it such as mysnowflake-myultracooldomainname.rhcloud.com). I think I need a very basic tutorial how to set things up related with config.js.

**Comment by bartonhammond** [comment]
I still don't know what error you are getting.  Please attach the log from running 'git push origin master'. 

 Also, note that the `config.js` isn't used extensively when pushing to OpenShift.  Take a look at `src/config/hapi.js` and you'll see that the environment variables set by OpenShift are used for the ip/port of the app itself.  

Then look at `src/database/mongodb.js` and you'll see the same approach.  The same is true for `src/database/redis.js`

**Comment by aferust** [comment]
I am so sorry, I forgot adding this:

remote: npm info ok
remote: Preparing build for deployment
remote: Deployment id is 309e17a3
remote: Activating deployment
remote: HAProxy already running
remote: CLIENT_RESULT: HAProxy instance is started
remote:   - Checking to see if Node.js version 4.2.3 is installed ...
remote:   - Node.js version 4.2.3 is already installed
remote:
remote:   - pre_start_nodejs: Adding Node.js version 4.2.3 binaries to path
remote:   - PATH set to include custom node version (4.2.3) from
remote:        /var/lib/openshift/578d22460c1e66346e00015c/app-root/data//node-v4.2.3-linux-x64/bin
remote:     PATH = /var/lib/openshift/578d22460c1e66346e00015c/app-root/data//node-v4.2.3-linux-x64/bin:/var/lib/openshift/578d22460c1e66346e00015c/app-root/runtime/repo/node_modules/.bin:/var/lib/openshift/578d22460c1e66346e00015c//.node_modules/.bin:/opt/rh/nodejs010/root/usr/bin:/var/lib/openshift/578d22460c1e66346e00015c/haproxy/usr/bin:/opt/rh/mongodb24/root/usr/bin:/bin:/usr/bin:/usr/sbin
remote: Starting NodeJS cartridge
remote: Mon Jul 18 2016 15:32:18 GMT-0400 (EDT): Starting application 'mysnowflake' ...
remote: Waiting for application port (8080) become available ...
remote: Application 'mysnowflake' failed to start (port 8080 not available)
remote: -------------------------
remote: Git Post-Receive Result: failure
remote: Activation status: failure
remote: Activation failed for the following gears:
remote: 578d22460c1e66346e00015c (Error activating gear: CLIENT_ERROR: Failed to execute: 'control start' for /var/lib/openshift/578d22460c1e66346e00015c/nodejs
remote: #IO:0x000000008772b0
remote: #IO:0x00000000877238
remote: )
remote: Deployment completed with status: failure
remote: postreceive failed
To ssh://578d22460c1e66346e00015c@mysnowflake-myultracooldomainname.rhcloud.com/~/git/mysnowflake.git/
   05e1d79..b2deec7  master -> master

**Comment by aferust** [comment]
Ok, it did not yield errors when I changed local ips in config.js to mysnowflake-myultracooldomainname.rhcloud.com. I admit that I am so stupid. Thank you.

**Comment by bartonhammond** [comment]
Ok thanks, but that doesn't help much.  What you'll need to do is ssh into your box and find the nodejs log.  You can use the `rsh` command from the prompt in your server root.  Once you get in, you need to look for the application logs.  I think it's something like `app/logs`.  

You can see a list of commands here: [https://developers.openshift.com/managing-your-applications/common-rhc-commands.html](https://developers.openshift.com/managing-your-applications/common-rhc-commands.html)

**Comment by bartonhammond** [comment]
Note that when you try to hook up the mobile client Snowflake, you'll need to update it's config.js to tell it 2 things, that you will use Hapi remote and the Hapi remote url.  But let's get the server up and running first.

**Comment by bartonhammond** [comment]
Here's  a note to help you get those logs:

> These can be collected by taking the SSH URL from the output of the `rhc app-show <APP-NAME>` command and use it in the below. This will create a file in /tmp/ titled 'log_files.tar.gz' that you can upload here. It will contain all logs necessary to investigate. This is assuming you are running on a linux/mac client:

 `$ scp -r SSH_URL:~/app-root/logs/ .; tar czvf /tmp/log_files.tar.gz logs/`

**Comment by bartonhammond** [comment]
Just a note about the above, what I did was `rsh` into my Openshift Gear and remove all the logs first, then redo the push, then run that command.  Otherwise the command above will pick up ALL the logs which could be large.  All we want at this time, is the last log of the push failure to start the app.

Note, to be able to remove the logs, you'll have to stop your application - use `rhc app-stop`, delete the logs, then `rhc app-start` and then run the `scp` command above

**Comment by bartonhammond** [comment]
Here's an example of getting the SSH_URL.  The name of my server is 'server'.  So I am in the openshift project and enter `rhc app-show server`.   Then I provide my password and then I see the SSH.  Use that value to log in w/ like this: `ssh 56d05ee17628e1f6080000bd@server-bartonhammond.rhcloud.com` would be mine.  Once logged in, you can do a `ls` and see the path `app-root\logs` and remove everything there (assuming you had stopped the app)

```
~/projects/MFV/snowflake-hapi-openshift (master)$ rhc app-show server
/usr/local/lib/ruby/gems/2.3.0/gems/commander-4.2.1/lib/commander/user_interaction.rb:328: warning: constant ::TimeoutError is deprecated
Your authorization token has expired. Please sign in now to continue on openshift.redhat.com.
Password: **********

server @ http://server-bartonhammond.rhcloud.com/ (uuid: 56d05ee17628e1f6080000bd)
----------------------------------------------------------------------------------
  Domain:     bartonhammond
  Created:    Feb 26  8:19 AM
  Gears:      3 (defaults to small)
  Git URL:    ssh://56d05ee17628e1f6080000bd@server-bartonhammond.rhcloud.com/~/git/server.git/
  SSH:        56d05ee17628e1f6080000bd@server-bartonhammond.rhcloud.com   <<<<<this
  Deployment: auto (on git push)

```

**Comment by aferust** [comment]
Hi Barton, you skipped my last message saying I have already get everything worked :) You gave me a lot of information for debugging though. I suggest you giving a little more details for creating config.js in the documents. Assignment of url variable for Hapi (remote) should be like:

```
      url: 'http://mysnowflake-yourDomain.rhcloud.com'
```

Thank you very much!

**Comment by bartonhammond** [comment]
Great @aferust - good to know it's working

**Comment by GarvSabharwal** [comment]
git.exe push --progress "origin" master:master

Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 282 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
remote: Stopping NodeJS cartridge
remote: Mon Aug 22 2016 01:56:38 GMT-0400 (EDT): Stopping application 'nodejs' ...
remote: Mon Aug 22 2016 01:56:39 GMT-0400 (EDT): Stopped Node application 'nodejs'
remote: Saving away previously installed Node modules
remote: Building git ref 'master', commit 1476ba6
remote: Building NodeJS cartridge
remote: npm info it worked if it ends with ok
remote: npm info using npm@2.14.13
remote: npm info using node@v0.10.35
remote: npm info preinstall OpenShift-Sample-App@1.0.0
remote: npm info build /var/lib/openshift/57ba8a780c1e668669000094/app-root/runtime/repo
remote: npm info linkStuff OpenShift-Sample-App@1.0.0
remote: npm info install OpenShift-Sample-App@1.0.0
remote: npm info postinstall OpenShift-Sample-App@1.0.0
remote: npm info prepublish OpenShift-Sample-App@1.0.0
remote: npm info ok
remote: Preparing build for deployment
remote: Deployment id is 368816b1
remote: Activating deployment
remote: Starting NodeJS cartridge
remote: Mon Aug 22 2016 01:57:15 GMT-0400 (EDT): Starting application 'nodejs' ...
remote: Waiting for application port (8080) become available ...
remote: Application 'nodejs' failed to start (port 8080 not available)
remote: -------------------------
remote: Git Post-Receive Result: failure
remote: Activation status: failure
remote: Activation failed for the following gears:
remote: 57ba8a780c1e668669000094 (Error activating gear: CLIENT_ERROR: Failed to execute: 'control start' for /var/lib/openshift/57ba8a780c1e668669000094/nodejs
remote: #IO:0x0000000153d3a0
remote: #IO:0x0000000153d328
remote: )
remote: Deployment completed with status: failure
remote: postreceive failed
To ssh://57ba8a780c1e668669000094@nodejs-sabharwal.rhcloud.com/~/git/nodejs.git
db61a84..1476ba6  master -> master

Success (119328 ms @ 8/22/2016 11:28:17 AM)
getting this error please help me

**Comment by bartonhammond** [comment]
@GarvSabharwal You will need to SSH into the RedHat site and look at the logs.  First log in to Redhat  Online and select your server.  Then, on the right had side is a "Remote Access" link that will display a 'ssh' command you run from the command line.  Once you are ssh'd into your remote server, you'll need to navigate to the 'logs' directory and look at the nodejs logs.  There may be multiple nodejs logs so you'll need to search for the one with the error.  One way to do this is to stop your app using `rhc app stop`, then on the remote server, delete all the logs, then back on the client, do `rhc app start`.  Then there will be a single nodejs log on the remote server.  Find that log file and post the relevant information here.
