### ISSUE TITLE
API Documentation link not working

### ISSUE THREAD

**Issue by agrass** [bartonhammond/snowflake-hapi-openshift#5]
Hello, where I can find the API documentation?? http://mysnowflake-bartonhammond.rhcloud.com/documentation url is not working. I want to replicate this on a RoR backend.

Thanks!

**Comment by bartonhammond** [comment]
Hi @agrass - Once you deploy your own app, "what-ever-you-call-it", then you'll have the documentation at `what-ever-you-call-it.<yourdomain>.rhcloud.com/documentation`

If you set the config.js file to use Hapi locally, you'll find the docs at `localhost:5000/documentation`

**Comment by agrass** [comment]
Ok Great, thanks!
